package parser

//These are the tags which use <tag> instead of just the text
var tagDirectiveRegex = `(?i)\b(` +
	`AuthnProviderAlias|AuthzProviderAlias|Directory|DirectoryMatch|Else|` +
	`ElseIf|Files|FilesMatch|If|IfDefine|IfDirective|IfFile|IfModule|IfSection|` +
	`IfVersion|Limit|LimitExcept|Location|LocationMatch|Macro|MDomainSet|Proxy|` +
	`ProxyMatch|RequireAll|RequireAny|RequireNone|VirtualHost` +
	`)\b`

//Every single directive from the documentation and mods
//Excluding the tags found above.
var directiveRegex = `(?i)^(` +
	`AcceptFilter|AcceptPathInfo|AccessFileName|Action|AddAlt|AddAltByEncoding|` +
	`AddAltByType|AddCharset|AddDefaultCharset|AddDescription|AddEncoding|AddHandler|` +
	`AddIcon|AddIconByEncoding|AddIconByType|AddInputFilter|AddLanguage|AddModuleInfo|` +
	`AddOutputFilter|AddOutputFilterByType|AddType|Alias|AliasMatch|Allow|AllowCONNECT|` +
	`AllowEncodedSlashes|AllowMethods|AllowOverride|AllowOverrideList|Anonymous|` +
	`Anonymous_LogEmail|Anonymous_MustGiveEmail|Anonymous_NoUserID|Anonymous_VerifyEmail|` +
	`AsyncRequestWorkerFactor|AuthBasicAuthoritative|AuthBasicFake|AuthBasicProvider|` +
	`AuthBasicUseDigestAlgorithm|AuthDBDUserPWQuery|AuthDBDUserRealmQuery|AuthDBMGroupFile|` +
	`AuthDBMType|AuthDBMUserFile|AuthDigestAlgorithm|AuthDigestDomain|AuthDigestNonceLifetime|` +
	`AuthDigestProvider|AuthDigestQop|AuthDigestShmemSize|AuthFormAuthoritative|AuthFormBody|` +
	`AuthFormDisableNoStore|AuthFormFakeBasicAuth|AuthFormLocation|AuthFormLoginRequiredLocation|` +
	`AuthFormLoginSuccessLocation|AuthFormLogoutLocation|AuthFormMethod|AuthFormMimetype|` +
	`AuthFormPassword|AuthFormProvider|AuthFormSitePassphrase|AuthFormSize|AuthFormUsername|` +
	`AuthGroupFile|AuthLDAPAuthorizePrefix|AuthLDAPBindAuthoritative|AuthLDAPBindDN|` +
	`AuthLDAPBindPassword|AuthLDAPCharsetConfig|AuthLDAPCompareAsUser|AuthLDAPCompareDNOnServer|` +
	`AuthLDAPDereferenceAliases|AuthLDAPGroupAttribute|AuthLDAPGroupAttributeIsDN|` +
	`AuthLDAPInitialBindAsUser|AuthLDAPInitialBindPattern|AuthLDAPMaxSubGroupDepth|` +
	`AuthLDAPRemoteUserAttribute|AuthLDAPRemoteUserIsDN|AuthLDAPSearchAsUser|` +
	`AuthLDAPSubGroupAttribute|AuthLDAPSubGroupClass|AuthLDAPURL|AuthMerging|AuthName|` +
	`AuthnCacheContext|AuthnCacheEnable|AuthnCacheProvideFor|AuthnCacheSOCache|AuthnCacheTimeout|` +
	`AuthnzFcgiCheckAuthnProvider|AuthnzFcgiDefineProvider|AuthType|AuthUserFile|` +
	`AuthzDBDLoginToReferer|AuthzDBDQuery|AuthzDBDRedirectQuery|AuthzDBMType|` +
	`AuthzSendForbiddenOnFailure|BalancerGrowth|BalancerInherit|BalancerMember|BalancerPersist|` +
	`BrotliAlterETag|BrotliCompressionMaxInputBlock|BrotliCompressionQuality|BrotliCompressionWindow|` +
	`BrotliFilterNote|BrowserMatch|BrowserMatchNoCase|BufferedLogs|BufferSize|CacheDefaultExpire|` +
	`CacheDetailHeader|CacheDirLength|CacheDirLevels|CacheDisable|CacheEnable|CacheFile|CacheHeader|` +
	`CacheIgnoreCacheControl|CacheIgnoreHeaders|CacheIgnoreNoLastMod|CacheIgnoreQueryString|` +
	`CacheIgnoreURLSessionIdentifiers|CacheKeyBaseURL|CacheLastModifiedFactor|CacheLock|` +
	`CacheLockMaxAge|CacheLockPath|CacheMaxExpire|CacheMaxFileSize|CacheMinExpire|CacheMinFileSize|` +
	`CacheNegotiatedDocs|CacheQuickHandler|CacheReadSize|CacheReadTime|CacheRoot|CacheSocache|` +
	`CacheSocacheMaxSize|CacheSocacheMaxTime|CacheSocacheMinTime|CacheSocacheReadSize|` +
	`CacheSocacheReadTime|CacheStaleOnError|CacheStoreExpired|CacheStoreNoStore|CacheStorePrivate|` +
	`CGIDScriptTimeout|CGIMapExtension|CGIPassAuth|CGIVar|CharsetDefault|CharsetOptions|` +
	`CharsetSourceEnc|CheckBasenameMatch|CheckCaseOnly|CheckSpelling|ChrootDir|ContentDigest|` +
	`CookieDomain|CookieExpires|CookieHTTPOnly|CookieName|CookieSameSite|CookieSecure|CookieStyle|` +
	`CookieTracking|CoreDumpDirectory|CustomLog|Dav|DavDepthInfinity|DavGenericLockDB|DavLockDB|` +
	`DavLockDiscovery|DavMinTimeout|DBDExptime|DBDInitSQL|DBDKeep|DBDMax|DBDMin|DBDParams|DBDPersist|` +
	`DBDPrepareSQL|DBDriver|DefaultIcon|DefaultLanguage|DefaultRuntimeDir|DefaultType|Define|` +
	`DeflateBufferSize|DeflateCompressionLevel|DeflateFilterNote|DeflateInflateLimitRequestBody|` +
	`DeflateInflateRatioBurst|DeflateInflateRatioLimit|DeflateMemLevel|DeflateWindowSize|Deny|` +
	`DirectoryCheckHandler|DirectoryIndex|DirectoryIndexRedirect|DirectorySlash|DocumentRoot|` +
	`DTracePrivileges|DumpIOInput|DumpIOOutput|EnableExceptionHook|EnableMMAP|EnableSendfile|Error|` +
	`ErrorDocument|ErrorLog|ErrorLogFormat|Example|ExpiresActive|ExpiresByType|ExpiresDefault|` +
	`ExtendedStatus|ExtFilterDefine|ExtFilterOptions|FallbackResource|FancyIndexing|FileETag|` +
	`FilterChain|FilterDeclare|FilterProtocol|FilterProvider|FilterTrace|FlushMaxPipelined|` +
	`FlushMaxThreshold|ForceLanguagePriority|ForceType|ForensicLog|GlobalLog|GprofDir|` +
	`GracefulShutdownTimeout|Group|H2CopyFiles|H2Direct|H2EarlyHints|H2MaxSessionStreams|` +
	`H2MaxWorkerIdleSeconds|H2MaxWorkers|H2MinWorkers|H2ModernTLSOnly|H2OutputBuffering|H2Padding|` +
	`H2Push|H2PushDiarySize|H2PushPriority|H2PushResource|H2SerializeHeaders|H2StreamMaxMemSize|` +
	`H2TLSCoolDownSecs|H2TLSWarmUpSize|H2Upgrade|H2WindowSize|Header|HeaderName|HeartbeatAddress|` +
	`HeartbeatListen|HeartbeatMaxServers|HeartbeatStorage|HostnameLookups|HttpProtocolOptions|` +
	`IdentityCheck|IdentityCheckTimeout|ImapBase|ImapDefault|ImapMenu|Include|IncludeOptional|` +
	`IndexHeadInsert|IndexIgnore|IndexIgnoreReset|IndexOptions|IndexOrderDefault|IndexStyleSheet|` +
	`InputSed|ISAPIAppendLogToErrors|ISAPIAppendLogToQuery|ISAPICacheFile|ISAPIFakeAsync|` +
	`ISAPILogNotSupported|ISAPIReadAheadBuffer|KeepAlive|KeepAliveTimeout|KeptBodySize|` +
	`LanguagePriority|LDAPCacheEntries|LDAPCacheTTL|LDAPConnectionPoolTTL|LDAPConnectionTimeout|` +
	`LDAPLibraryDebug|LDAPOpCacheEntries|LDAPOpCacheTTL|LDAPReferralHopLimit|LDAPReferrals|` +
	`LDAPRetries|LDAPRetryDelay|LDAPSharedCacheFile|LDAPSharedCacheSize|LDAPTimeout|` +
	`LDAPTrustedClientCert|LDAPTrustedGlobalCert|LDAPTrustedMode|LDAPVerifyServerCert|` +
	`LimitInternalRecursion|LimitRequestBody|LimitRequestFields|LimitRequestFieldSize|` +
	`LimitRequestLine|LimitXMLRequestBody|Listen|ListenBackLog|ListenBacklog|ListenCoresBucketsRatio|` +
	`LoadFile|LoadModule|LogFormat|LogIOTrackTTFB|LogLevel|LogMessage|LuaAuthzProvider|LuaCodeCache|` +
	`LuaHookAccessChecker|LuaHookAuthChecker|LuaHookCheckUserID|LuaHookFixups|LuaHookInsertFilter|` +
	`LuaHookLog|LuaHookMapToStorage|LuaHookPreTranslate|LuaHookTranslateName|LuaHookTypeChecker|` +
	`LuaInherit|LuaInputFilter|LuaMapHandler|LuaOutputFilter|LuaPackageCPath|LuaPackagePath|` +
	`LuaQuickHandler|LuaRoot|LuaScope|MaxConnectionsPerChild|MaxKeepAliveRequests|MaxMemFree|` +
	`MaxRangeOverlaps|MaxRangeReversals|MaxRanges|MaxRequestWorkers|MaxSpareServers|MaxSpareThreads|` +
	`MaxThreads|MDActivationDelay|MDBaseServer|MDCAChallenges|MDCertificateAgreement|` +
	`MDCertificateAuthority|MDCertificateCheck|MDCertificateFile|MDCertificateKeyFile|` +
	`MDCertificateMonitor|MDCertificateProtocol|MDCertificateStatus|MDChallengeDns01|MDContactEmail|` +
	`MDDriveMode|MDExternalAccountBinding|MDHttpProxy|MDMember|MDMembers|MDMessageCmd|MDMustStaple|` +
	`MDNotifyCmd|MDomain|MDPortMap|MDPrivateKeys|MDRenewMode|MDRenewWindow|MDRequireHttps|` +
	`MDRetryDelay|MDRetryFailover|MDServerStatus|MDStapleOthers|MDStapling|MDStaplingKeepResponse|` +
	`MDStaplingRenewWindow|MDStoreDir|MDStoreLocks|MDWarnWindow|MemcacheConnTTL|MergeSlashes|` +
	`MergeTrailers|MetaDir|MetaFiles|MetaSuffix|MimeMagicFile|MinSpareServers|MinSpareThreads|` +
	`MMapFile|ModemStandard|ModMimeUsePathInfo|MultiviewsMatch|Mutex|NameVirtualHost|NoProxy|` +
	`NWSSLTrustedCerts|NWSSLUpgradeable|Options|Order|OutputSed|PassEnv|PidFile|PrivilegesMode|` +
	`Protocol|ProtocolEcho|Protocols|ProtocolsHonorOrder|Proxy100Continue|ProxyAddHeaders|` +
	`ProxyBadHeader|ProxyBlock|ProxyDomain|ProxyErrorOverride|ProxyExpressDBMFile|ProxyExpressDBMType|` +
	`ProxyExpressEnable|ProxyFCGIBackendType|ProxyFCGISetEnvIf|ProxyFtpDirCharset|` +
	`ProxyFtpEscapeWildcards|ProxyFtpListOnWildcard|ProxyHCExpr|ProxyHCTemplate|ProxyHCTPsize|` +
	`ProxyHTMLBufSize|ProxyHTMLCharsetOut|ProxyHTMLDocType|ProxyHTMLEnable|ProxyHTMLEvents|` +
	`ProxyHTMLExtended|ProxyHTMLFixups|ProxyHTMLInterp|ProxyHTMLLinks|ProxyHTMLMeta|` +
	`ProxyHTMLStripComments|ProxyHTMLURLMap|ProxyIOBufferSize|ProxyMaxForwards|ProxyPass|` +
	`ProxyPassInherit|ProxyPassInterpolateEnv|ProxyPassMatch|ProxyPassReverse|` +
	`ProxyPassReverseCookieDomain|ProxyPassReverseCookiePath|ProxyPreserveHost|` +
	`ProxyReceiveBufferSize|ProxyRemote|ProxyRemoteMatch|ProxyRequests|ProxySCGIInternalRedirect|` +
	`ProxySCGISendfile|ProxySet|ProxySourceAddress|ProxyStatus|ProxyTimeout|ProxyVia|` +
	`ProxyWebsocketFallbackToProxyHttp|QualifyRedirectURL|ReadBufferSize|ReadmeName|` +
	`ReceiveBufferSize|Redirect|RedirectMatch|RedirectPermanent|RedirectTemp|RedisConnPoolTTL|` +
	`RedisTimeout|ReflectorHeader|RegexDefaultOptions|RegisterHttpMethod|RemoteIPHeader|` +
	`RemoteIPInternalProxy|RemoteIPInternalProxyList|RemoteIPProxiesHeader|RemoteIPProxyProtocol|` +
	`RemoteIPProxyProtocolExceptions|RemoteIPTrustedProxy|RemoteIPTrustedProxyList|RemoveCharset|` +
	`RemoveEncoding|RemoveHandler|RemoveInputFilter|RemoveLanguage|RemoveOutputFilter|RemoveType|` +
	`RequestHeader|RequestReadTimeout|Require|RewriteBase|RewriteCond|RewriteEngine|RewriteLog|` +
	`RewriteLogLevel|RewriteMap|RewriteOptions|RewriteProxy|RewriteReferee|RewriteRule|RLimitCPU|` +
	`RLimitMEM|RLimitNPROC|Satisfy|ScoreBoardFile|Script|ScriptAlias|ScriptAliasMatch|` +
	`ScriptInterpreterSource|ScriptLog|ScriptLogBuffer|ScriptLogLength|ScriptSock|SecureListen|` +
	`SeeRequestTail|SendBufferSize|ServerAdmin|ServerAlias|ServerLimit|ServerName|ServerPath|` +
	`ServerRoot|ServerSignature|ServerTokens|Session|SessionCookieName|SessionCookieName2|` +
	`SessionCookieRemove|SessionCryptoCipher|SessionCryptoDriver|SessionCryptoPassphrase|` +
	`SessionCryptoPassphraseFile|SessionDBDCookieName|SessionDBDCookieName2|` +
	`SessionDBDCookieRemove|SessionDBDDeleteLabel|SessionDBDInsertLabel|SessionDBDPerUser|` +
	`SessionDBDSelectLabel|SessionDBDUpdateLabel|SessionEnv|SessionExclude|` +
	`SessionExpiryUpdateInterval|SessionHeader|SessionInclude|SessionMaxAge|SetEnv|SetEnvIf|` +
	`SetEnvIfExpr|SetEnvIfNoCase|SetHandler|SetInputFilter|SetOutputFilter|SSIEndTag|SSIErrorMsg|` +
	`SSIETag|SSILastModified|SSILegacyExprParser|SSIStartTag|SSITimeFormat|SSIUndefinedEcho|` +
	`SSLCACertificateFile|SSLCACertificatePath|SSLCADNRequestFile|SSLCADNRequestPath|` +
	`SSLCARevocationCheck|SSLCARevocationFile|SSLCARevocationPath|SSLCertificateChainFile|` +
	`SSLCertificateFile|SSLCertificateKeyFile|SSLCipherSuite|SSLCompression|SSLCryptoDevice|` +
	`SSLEngine|SSLFIPS|SSLHonorCipherOrder|SSLInsecureRenegotiation|SSLOCSPDefaultResponder|` +
	`SSLOCSPEnable|SSLOCSPNoverify|SSLOCSPOverrideResponder|SSLOCSPProxyURL|` +
	`SSLOCSPResponderCertificateFile|SSLOCSPResponderTimeout|SSLOCSPResponseMaxAge|` +
	`SSLOCSPResponseTimeSkew|SSLOCSPUseRequestNonce|SSLOpenSSLConfCmd|SSLOptions|` +
	`SSLPassPhraseDialog|SSLProtocol|SSLProxyCACertificateFile|SSLProxyCACertificatePath|` +
	`SSLProxyCARevocationCheck|SSLProxyCARevocationFile|SSLProxyCARevocationPath|` +
	`SSLProxyCheckPeerCN|SSLProxyCheckPeerExpire|SSLProxyCheckPeerName|SSLProxyCipherSuite|` +
	`SSLProxyEngine|SSLProxyMachineCertificateChainFile|SSLProxyMachineCertificateFile|` +
	`SSLProxyMachineCertificatePath|SSLProxyProtocol|SSLProxyVerify|SSLProxyVerifyDepth|` +
	`SSLRandomSeed|SSLRenegBufferSize|SSLRequire|SSLRequireSSL|SSLSessionCache|` +
	`SSLSessionCacheTimeout|SSLSessionTicketKeyFile|SSLSessionTickets|SSLSRPUnknownUserSeed|` +
	`SSLSRPVerifierFile|SSLStaplingCache|SSLStaplingErrorCacheTimeout|SSLStaplingFakeTryLater|` +
	`SSLStaplingForceURL|SSLStaplingResponderTimeout|SSLStaplingResponseMaxAge|` +
	`SSLStaplingResponseTimeSkew|SSLStaplingReturnResponderErrors|SSLStaplingStandardCacheTimeout|` +
	`SSLStrictSNIVHostCheck|SSLUserName|SSLUseStapling|SSLVerifyClient|SSLVerifyDepth|StartServers|` +
	`StartThreads|StrictHostCheck|Substitute|SubstituteInheritBefore|SubstituteMaxLineLength|` +
	`Suexec|SuexecUserGroup|ThreadLimit|ThreadsPerChild|ThreadStackSize|TimeOut|TLSCertificate|` +
	`TLSCiphersPrefer|TLSCiphersSuppress|TLSEngine|TLSHonorClientOrder|TLSOptions|TLSProtocol|` +
	`TLSProxyCA|TLSProxyCiphersPrefer|TLSProxyCiphersSuppress|TLSProxyEngine|TLSProxyMachineCertificate|` +
	`TLSProxyProtocol|TLSSessionCache|TLSStrictSNI|TraceEnable|TransferLog|TypesConfig|UnDefine|` +
	`UndefMacro|UnsetEnv|Use|UseCanonicalName|UseCanonicalPhysicalPort|User|UserDir|VHostCGIMode|` +
	`VHostCGIPrivs|VHostGroup|VHostPrivs|VHostSecure|VHostUser|VirtualDocumentRoot|` +
	`VirtualDocumentRootIP|VirtualScriptAlias|VirtualScriptAliasIP|WatchdogInterval|XBitHack|` +
	`xml2EncAlias|xml2EncDefault|xml2StartParse` +
	`)(?:[ \t])`
